In [2]:
'''
numpy <- numerical python
Steps we performed in vectorized operations for analytics
1. adding elemens
2. Multiplying elements
3. coditional subsetting
4. Get summary statistics
'''

'\nnumpy <- numerical python\nSteps we performed in vectorized operations for analytics\n1. adding elemens\n2. Multiplying elements\n3. coditional subsetting\n4. get summary statistics\n'

In [3]:
x = [10,20,30,40,50]

# Different ways in which we can multiply every element by 10

# Method 1 : map
print(list(map(lambda i: i*10,x)))

# Method 2 : List comprehenion
[i*10 for i in x]


[100, 200, 300, 400, 500]


[100, 200, 300, 400, 500]

In [4]:
# Method 3 : Numpy

import numpy as np

nparray = np.array(x)
print(nparray*10)

[100 200 300 400 500]


In [9]:
x = [10,20,'Hi','Hello',2.5]
print(np.array(x))

['10' '20' 'Hi' 'Hello' '2.5']


In [17]:
print(nparray[0])
print(nparray[3])
print(nparray[-1])
print(nparray[2:4])
print(nparray[1::1])

10
40
50
[30 40]
[20 30 40 50]


In [20]:
print(nparray[nparray>=30])

[30 40 50]


In [31]:
print("Sum : ",nparray.sum())
print("Product : ",nparray.prod())
print("Min : ",nparray.min())
print("Max : ",nparray.max())
print("Mean : ",nparray.mean())
print("Position of max element : ",nparray.argmax())

Sum :  150
Product :  12000000
Min :  10
Max :  50
Mean :  30.0
Position of max element :  4


In [23]:
[[1,2,3],[4,5,6]]

[[1, 2, 3], [4, 5, 6]]

In [13]:
num1 = np.array([[1,2,3],[4,5,6]])
print(num1)
print(type(num1))
print(num1.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [26]:
num[1][0]

4

In [27]:
[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

In [10]:
num = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(num)
print(type(num))
print(num.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
(2, 2, 3)


In [33]:
num[1][1][1]

11

In [36]:
npx = np.array([[1,2,3],[4,5,6]])
print(npx)

# Subtract every element of npx by 2 :
print(npx-2)

# Multiply every element of npx by itself
print(npx*npx)

# Subtract every element of npx from the mean
print(npx.mean()-npx)


[[1 2 3]
 [4 5 6]]
[[-1  0  1]
 [ 2  3  4]]
[[ 1  4  9]
 [16 25 36]]
[[ 2.5  1.5  0.5]
 [-0.5 -1.5 -2.5]]


In [14]:
p = list(range(1,10))
print(p)
print(type(p))
x = np.arange(10)
print(x)
print(type(x))
print(x.shape)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)


In [72]:
xl = x.reshape([5,2])
print(xl)
xl1 = xl.reshape([1,10])
print(xl1)
xl1.shape

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4 5 6 7 8 9]]


(1, 10)

In [59]:
xl.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
y = np.arange(8)
print(y)
z = y.reshape([2,2,2])
print(z)
z.shape

[0 1 2 3 4 5 6 7]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


(2, 2, 2)

In [89]:
y = np.arange(9)
y1 = y.reshape([3,3])
print(y1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
nparray1 = np.array([[1,2,3],[4,5,6]])
nparray2 = np.array([[7,8,9],[10,11,12]])
len(nparray2)
print(nparray2.shape)

(2, 3)


In [131]:
# rbind of R
print(np.concatenate([nparray1,nparray2],axis = 0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [132]:
# cbind of R
print(np.concatenate([nparray1,nparray2],axis = 1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [18]:
print(np.hstack((nparray1,nparray2)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [129]:
print(np.vstack((nparray1,nparray2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [104]:
outcome = np.random.randint(1,7,size=10)
print(outcome)

[6 1 1 3 2 5 2 3 3 5]


In [105]:
outcome = np.random.randint(1,7,size=(3,3))
print(outcome)

[[4 4 3]
 [1 6 2]
 [1 4 2]]


In [106]:
x = [99,75,65,29]
np.sort(x)

array([29, 65, 75, 99])

In [114]:
x = [10,11,12,34]
np.random.shuffle(x)
print(x)

[10, 12, 34, 11]


In [115]:
x = [99,11,12,34]
a = np.array(x)
-np.sort(-a)

array([99, 34, 12, 11])

In [118]:
nparray1 = np.array([[1,2,3],[4,5,6]])
nparray2 = np.array([[7,8,9],[10,11,12]])
nparray = np.concatenate([nparray1,nparray2],axis = 1)
print(nparray)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [126]:
print(np.split(nparray,2,axis = 0))

[array([[1, 2, 3, 7, 8, 9]]), array([[ 4,  5,  6, 10, 11, 12]])]


In [124]:
print(np.split(nparray,2,axis = 1))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [127]:
print(np.split(nparray,3,axis = 1))

[array([[1, 2],
       [4, 5]]), array([[ 3,  7],
       [ 6, 10]]), array([[ 8,  9],
       [11, 12]])]


# PANDA'S

In [133]:
'''
Pandas <- Python and data analysis
1. Pandas series
2. Pandas dataframe
'''

'\nPandas <- Python and data analysis\n1. Pandas series\n2. Pandas dataframe\n'

In [35]:
import pandas as pd
import numpy as np

In [138]:
pandas_series = pd.Series([4,8,9.0,10])
print(pandas_series)

0     4.0
1     8.0
2     9.0
3    10.0
dtype: float64


In [159]:
pandas_series = pd.Series([4,8,9.0,10,"Hello"])
#type(pandas_series[5])
print(pandas_series)
#s = pandas_series[type(pandas_series)==str]
#print(s)

0        4
1        8
2        9
3       10
4    Hello
dtype: object


In [150]:
series = pd.Series([4,8,9.0,10,-4],
                    index = ['a','b','c','d','e'])
print(series)

a     4.0
b     8.0
c     9.0
d    10.0
e    -4.0
dtype: float64


In [151]:
series[0]

4.0

In [152]:
series['a']

4.0

In [153]:
series[series>3.0]

a     4.0
b     8.0
c     9.0
d    10.0
dtype: float64

In [162]:
pd.Series([[10.5,7.5,6],[3.5,2.5],2.5,7.5])

0    [10.5, 7.5, 6]
1        [3.5, 2.5]
2               2.5
3               7.5
dtype: object

In [163]:
a = pd.Series([10,20,30,'40'])
b = pd.Series([1,2,3,'4'])
a+b

0     11
1     22
2     33
3    404
dtype: object

In [178]:
d = {"First":["Hi","Hello"],
    "Second" : 5.4,
    "Third" : -9.4,
    "Fourth" : 12}
ps = pd.Series(d)
print(ps)

First     [Hi, Hello]
Fourth             12
Second            5.4
Third            -9.4
dtype: object


In [177]:
data = {"date": ['December,2014','December,2013',
                'December,2012','December,2011'],
       "global_temp" : [0.87,0.74,0.65,0.63]
       }
dataframe = pd.DataFrame(data)
print(dataframe)

            date  global_temp
0  December,2014         0.87
1  December,2013         0.74
2  December,2012         0.65
3  December,2011         0.63


In [36]:
data = {"date": ['December,2014','December,2013',
                'December,2012','December,2011'],
       "global_temp" : [0.87,0.74,0.65,0.63]
       }
dataframe = pd.DataFrame(data, index= ["a","b","c","d"])
print(dataframe)

            date  global_temp
a  December,2014         0.87
b  December,2013         0.74
c  December,2012         0.65
d  December,2011         0.63


In [40]:
dataframe['date']

a    December,2014
b    December,2013
c    December,2012
d    December,2011
Name: date, dtype: object

In [182]:
dataframe.date

a    December,2014
b    December,2013
c    December,2012
d    December,2011
Name: date, dtype: object

In [191]:
dataframe = pd.DataFrame(np.random.randn(20,5),
                        columns = ["A","B","C","D","E"])
print(dataframe)

           A         B         C         D         E
0   0.061399  0.078644 -0.928876 -0.546191 -1.275555
1   0.272194 -1.574170 -0.766130 -0.126915  0.831661
2  -0.800926  0.003320 -1.122928  0.062194  0.961414
3  -1.203118  0.542948 -1.144679  1.553330  0.916787
4   0.083357  0.575197  0.131813  0.146663 -0.523276
5  -0.628643  1.095735 -0.109996  0.554068 -1.161856
6   1.117686 -0.215748 -1.522985 -0.143281 -0.222980
7  -0.541070  0.686232 -0.367623 -1.655012  0.358179
8  -1.479648  0.393919 -2.051435 -0.331124  0.405524
9  -0.129747  0.888455 -0.534944 -1.563514  0.257788
10  0.221702  1.524043  0.958828 -0.257999  0.326718
11 -0.502818 -0.373714  0.007005 -0.105950  1.431032
12  0.725029 -0.049140  0.520375  0.440946  0.601990
13 -0.025812 -0.745507  0.252128 -0.896282  0.333275
14  0.301218  0.448424  0.431546  1.375622  0.777321
15 -2.177452 -0.314496 -1.323724  1.369902 -1.000907
16  0.455271  2.597863 -0.973377 -0.257482 -0.136290
17  0.931644 -0.318531  0.871648 -1.596025 -0.

In [192]:
dataframe.head()

A         B         C         D         E
0  0.061399  0.078644 -0.928876 -0.546191 -1.275555
1  0.272194 -1.574170 -0.766130 -0.126915  0.831661
2 -0.800926  0.003320 -1.122928  0.062194  0.961414
3 -1.203118  0.542948 -1.144679  1.553330  0.916787
4  0.083357  0.575197  0.131813  0.146663 -0.523276

In [195]:
dataframe.head(n=2)

A         B         C         D         E
0  0.061399  0.078644 -0.928876 -0.546191 -1.275555
1  0.272194 -1.574170 -0.766130 -0.126915  0.831661

In [193]:
dataframe.tail() # Default is 5 rows

A         B         C         D         E
15 -2.177452 -0.314496 -1.323724  1.369902 -1.000907
16  0.455271  2.597863 -0.973377 -0.257482 -0.136290
17  0.931644 -0.318531  0.871648 -1.596025 -0.060696
18  0.819551 -0.144978  0.487312 -0.231393  1.233723
19 -1.308581 -0.142906 -1.233566 -4.026780 -0.051027

In [197]:
dataframe.describe()

A          B          C          D          E
count  20.000000  20.000000  20.000000  20.000000  20.000000
mean   -0.190438   0.247779  -0.420980  -0.311761   0.200141
std     0.879935   0.881295   0.861877   1.259828   0.764201
min    -2.177452  -1.574170  -2.051435  -4.026780  -1.275555
25%    -0.671714  -0.240435  -1.128366  -0.633714  -0.157963
50%     0.017794   0.040982  -0.451283  -0.187337   0.329997
75%     0.339732   0.602956   0.296982   0.220233   0.790906
max     1.117686   2.597863   0.958828   1.553330   1.431032

In [198]:
dataframe.sort_values(by='C').head()

A         B         C         D         E
8  -1.479648  0.393919 -2.051435 -0.331124  0.405524
6   1.117686 -0.215748 -1.522985 -0.143281 -0.222980
15 -2.177452 -0.314496 -1.323724  1.369902 -1.000907
19 -1.308581 -0.142906 -1.233566 -4.026780 -0.051027
3  -1.203118  0.542948 -1.144679  1.553330  0.916787

In [201]:
# Get the 5 records of column A

dataframe.A.head(5)

0    0.061399
1    0.272194
2   -0.800926
3   -1.203118
4    0.083357
Name: A, dtype: float64

In [205]:
dataframe[1:4]

A         B         C         D         E
1  0.272194 -1.574170 -0.766130 -0.126915  0.831661
2 -0.800926  0.003320 -1.122928  0.062194  0.961414
3 -1.203118  0.542948 -1.144679  1.553330  0.916787

In [216]:
dataframe[1:3][['B','C','D']]

B         C         D
1 -1.57417 -0.766130 -0.126915
2  0.00332 -1.122928  0.062194

In [223]:
dataframe[['B','C','D']][1:3]

B         C         D
1 -1.57417 -0.766130 -0.126915
2  0.00332 -1.122928  0.062194

In [227]:
dataframe.iloc[[2,3,8,15],[0,1]]

A         B
2  -0.800926  0.003320
3  -1.203118  0.542948
8  -1.479648  0.393919
15 -2.177452 -0.314496

In [233]:
dataframe.iloc[range(0,6),[0,3]]

A         D
0  0.061399 -0.546191
1  0.272194 -0.126915
2 -0.800926  0.062194
3 -1.203118  1.553330
4  0.083357  0.146663
5 -0.628643  0.554068

In [247]:
# Get all the rows for column A and B

dataframe[["A","B"]] # Method 1

A         B
0   0.061399  0.078644
1   0.272194 -1.574170
2  -0.800926  0.003320
3  -1.203118  0.542948
4   0.083357  0.575197
5  -0.628643  1.095735
6   1.117686 -0.215748
7  -0.541070  0.686232
8  -1.479648  0.393919
9  -0.129747  0.888455
10  0.221702  1.524043
11 -0.502818 -0.373714
12  0.725029 -0.049140
13 -0.025812 -0.745507
14  0.301218  0.448424
15 -2.177452 -0.314496
16  0.455271  2.597863
17  0.931644 -0.318531
18  0.819551 -0.144978
19 -1.308581 -0.142906

In [249]:
dataframe.iloc[range(0,20),[0,1]]  # Method 2

A         B
0   0.061399  0.078644
1   0.272194 -1.574170
2  -0.800926  0.003320
3  -1.203118  0.542948
4   0.083357  0.575197
5  -0.628643  1.095735
6   1.117686 -0.215748
7  -0.541070  0.686232
8  -1.479648  0.393919
9  -0.129747  0.888455
10  0.221702  1.524043
11 -0.502818 -0.373714
12  0.725029 -0.049140
13 -0.025812 -0.745507
14  0.301218  0.448424
15 -2.177452 -0.314496
16  0.455271  2.597863
17  0.931644 -0.318531
18  0.819551 -0.144978
19 -1.308581 -0.142906

In [244]:
# Select 2nd to 4rth rows of column A

dataframe.iloc[range(1,5),[0]] # Method 1

A
1  0.272194
2 -0.800926
3 -1.203118
4  0.083357

In [248]:
# Method 2 :
dataframe[2:5].A

2   -0.800926
3   -1.203118
4    0.083357
Name: A, dtype: float64

In [252]:
# For all A values > 0.5, get the values of column A,B and C
# dataframe[condition for filtering][list of column names]
# Use & for and, | for or

dataframe[dataframe.A>0.5][["A","B","C"]]

A         B         C
6   1.117686 -0.215748 -1.522985
12  0.725029 -0.049140  0.520375
17  0.931644 -0.318531  0.871648
18  0.819551 -0.144978  0.487312

In [256]:
# For all A>0.5 and B>0.3,get values of columns A, B and C

dataframe[(dataframe.A>0.5) & (dataframe.B>0.3)][["A","B","C"]]

Empty DataFrame
Columns: [A, B, C]
Index: []

In [261]:
df = pd.DataFrame({'class' : ['a','a','b','b'],
                  'class_Name' : ['Marker','Marker','Projector','Projector'],
                  'quantity' : [12,10,3,6],
                  'price' : [120,100,30,60]})
df

class class_Name  price  quantity
0     a     Marker    120        12
1     a     Marker    100        10
2     b  Projector     30         3
3     b  Projector     60         6

In [262]:
# Find the mean of quantity
df.quantity.mean()

7.75

In [263]:
# For every class find the mean of quantity and price

grouped = df.groupby('class')
grouped.mean()

price  quantity
class                 
a      110.0      11.0
b       45.0       4.5

In [264]:
df.groupby('class').mean()

price  quantity
class                 
a      110.0      11.0
b       45.0       4.5

In [269]:
# For every class find the sum of quantity and mean of price

df.groupby('class').agg({'quantity' : np.sum,'price' : np.mean})

quantity  price
class                 
a            22    110
b             9     45

In [277]:
# For every class, find the mean, sum and std of price

df[['class','price']].groupby('class').agg(['mean','sum','std'])

price                
       mean  sum        std
class                      
a       110  220  14.142136
b        45   90  21.213203

In [278]:
# For every class, find the mean, sum and std of price and quantity

df[['class','price','quantity']].groupby('class').agg(['mean','sum','std'])

price                 quantity              
       mean  sum        std     mean sum       std
class                                             
a       110  220  14.142136     11.0  22  1.414214
b        45   90  21.213203      4.5   9  2.121320

In [280]:
df.groupby('class').agg(['mean','sum','std'])

price                 quantity              
       mean  sum        std     mean sum       std
class                                             
a       110  220  14.142136     11.0  22  1.414214
b        45   90  21.213203      4.5   9  2.121320

In [288]:
# For every class find the sum of quantity and mean of price

df.groupby(['class','class_Name']).\
agg({'quantity' : np.sum,'price' : np.mean})

quantity  price
class class_Name                 
a     Marker            22    110
b     Projector          9     45

In [289]:
dataframe.apply(np.mean,axis=0)

A   -0.190438
B    0.247779
C   -0.420980
D   -0.311761
E    0.200141
dtype: float64

In [290]:
dataframe.apply(np.mean,axis=1)

0    -0.522116
1    -0.272672
2    -0.179385
3     0.133054
4     0.082751
5    -0.050138
6    -0.197462
7    -0.303859
8    -0.612553
9    -0.216392
10    0.554658
11    0.091111
12    0.447840
13   -0.216440
14    0.666826
15   -0.689335
16    0.337197
17   -0.034392
18    0.432843
19   -1.352572
dtype: float64